version: "3.9"
services:
  mongo-service:
    image: "mongo:4.2.8"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/var/lib/mongodb/data"

  api:
    build: ./api
    environment:
      - PORT=3000
    volumes:
      - ./api:/api:delegated
      - rails_log:/api/log
      # don't mount tmp directory
      - /api/tmp
      - ./api/storage:/rails/storage
    ports:
      - "3000:3000"
    depends_on:
      - mongo-service

volumes:
  mongodb:
  rails_log:
